/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingMachine;

import javafx.application.Application;
import javafx.stage.Stage;
import vendingMachine.database.DatabaseToolkit;
import vendingMachine.model.MachineEngine;
import vendingMachine.model.MachineEngineImp;
import vendingMachine.views.MachineWindow;

import java.io.IOException;

//import java.sql.*;

public class App extends Application{
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException {
        primaryStage.setTitle("Vending Machine");
        primaryStage.setWidth(640);
        primaryStage.setHeight(420);
        primaryStage.setResizable(false);
        DatabaseToolkit dbt = new DatabaseToolkit();
        dbt.createConn();
        MachineEngine engine = new MachineEngineImp(dbt);
        MachineWindow window = new MachineWindow(engine,640,400,primaryStage);
        primaryStage.setScene(window.getScene());
        primaryStage.show();
    }
}
